<?php

namespace Ring\KafkaWrapper\Tests;

use \Orchestra\Testbench\TestCase as OrchestraTestCase;
use Ring\KafkaWrapper\KafkaWrapperServiceProvider;

class TestCase extends OrchestraTestCase{
    protected function getPackageProviders($app)
    {
        return [
            KafkaWrapperServiceProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {

    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }
}
